cmake_minimum_required(VERSION 3.20 FATAL_ERROR)
project(ASYNC_API LANGUAGES CXX)

# will fetch stdexec, disabled by default
# add_subdirectory(App_Senders)
# add_subdirectory(CH090_senders_basic)
# add_subdirectory(CH091_senders_curl)

add_subdirectory(App_Blocking)
add_subdirectory(App_Callbacks)
add_subdirectory(App_Coroutines)
add_subdirectory(App_Fibers)
add_subdirectory(App_Polling)
add_subdirectory(App_Tasks)
add_subdirectory(CH00_cmake)
add_subdirectory(CH01_libcurl_easy)
add_subdirectory(CH02_libcurl_multi)
add_subdirectory(CH051_coro_basic_task)
add_subdirectory(CH052_coro_basic_await)
add_subdirectory(CH053_coro_curl0)
add_subdirectory(CH054_coro_curl)
add_subdirectory(CH055_coro_task)
add_subdirectory(CH056_coro_await_task)
add_subdirectory(CH057_coro_await_all)
add_subdirectory(CH058_coro_await_curl)
add_subdirectory(CH059_coro_await_many)
add_subdirectory(CH060_fiber_basic)
add_subdirectory(CH062_fiber_switch)
add_subdirectory(CH064_fiber_callback)
add_subdirectory(CH065_fiber_task)
add_subdirectory(CH067_fiber_await_curl)
add_subdirectory(CH068_fiber_await_many)
add_subdirectory(CH070_future)
add_subdirectory(CH080_task_basic)
add_subdirectory(CH081_task_curl)
add_subdirectory(CH082_task_many)
add_subdirectory(CH092_senders_simple)
add_subdirectory(CH093_senders_when_all)
add_subdirectory(CH094_senders_sequence)
add_subdirectory(CH095_senders_curlv2)
